services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.16.3
    privileged: true
    shm_size: "512mb"
    volumes:
      - ./config.yml:/config/config.yml:ro # Tu lógica de conteo aquí
      - /mnt/storage/frigate:/media/frigate # Donde guardas el video en el ProLiant
    ports:
      - "5000:5000"
      - "8971:8971" # Puerto para acceso con contraseña
