services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.16.3
    privileged: true
    shm_size: "1gb"
    restart: unless-stopped
    volumes:
      - ./config.yml:/config/config.yml:ro
      - ./frigate_db:/config/db
      - /mnt/storage/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro
    networks:
      - dokploy-network
    ports:
      # - "8971:8971" # Quitamos esto definitivamente para evitar el error de puerto ocupado
      - "8554:8554" # RTSP
      - "8555:8555/tcp" # WebRTC
      - "8555:8555/udp" # WebRTC
    environment:
      - FRIGATE_RTSP_PASSWORD=password
      - PLUS_API_KEY= # Opcional si usas Frigate+

networks:
  dokploy-network:
    external: true
