services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.16.3
    privileged: true
    shm_size: "1gb"
    restart: unless-stopped
    network_mode: host # Crucial para ver c√°maras locales 192.168.x.x
    volumes:
      - ./config.yml:/config/config.yml:ro
      - ./frigate_db:/config/db
      - /mnt/storage/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FRIGATE_RTSP_PASSWORD=password
      - FRIGATE_HTTP_PORT=5000
