services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.16.3
    privileged: true
    shm_size: "2gb"
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.yml:/config/config.yml:ro
      - ./frigate_db:/database # Para evitar colisiones en /config
      - /mnt/storage/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FRIGATE_RTSP_PASSWORD=password
