services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.16.3
    privileged: true
    shm_size: "2gb" # Aumentado a 2GB para soportar 16 c√°maras sin crasheos
    restart: unless-stopped
    volumes:
      - ./config.yml:/config/config.yml:ro
      - ./frigate_db:/config/db
      - /mnt/storage/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5000:5000" # HTTP
      - "8554:8554" # RTSP
      - "8555:8555/tcp" # WebRTC
      - "8555:8555/udp" # WebRTC
    environment:
      - FRIGATE_RTSP_PASSWORD=password
      - FRIGATE_HTTP_PORT=5000
    networks:
      - dokploy-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  dokploy-network:
    external: true
