services:
  scrypted:
    container_name: scrypted
    image: koush/scrypted
    restart: unless-stopped
    networks:
      - dokploy-network
    volumes:
      - ../files/scrypted:/server/volume
    ports:
      - "11080:11080"
      - "10443:10443"
    privileged: true
    environment:
      - SCRYPTED_WEB_PORT=11080
      - SCRYPTED_SECURE_PORT=10443

networks:
  dokploy-network:
    external: true
