services:
  scrypted:
    container_name: scrypted
    image: koush/scrypted
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /home/maccell/scrypted/config:/server/volume
    ports:
      - "11080:11080"
      - "10443:10443" # Puerto HTTPS de Scrypted
      - "30000-30010:30000-30010" # Recomendado para streaming
    privileged: true
    environment:
      - SCRYPTED_WEB_PORT=11080
