services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.16.3
    container_name: frigate
    privileged: true
    shm_size: "2gb" # Aumentado a 2GB para soportar 16 c√°maras sin crasheos
    restart: unless-stopped
    volumes:
      - ./config.yml:/config/config.yml:ro
      - ./frigate_db:/config/db
      - /mnt/storage/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FRIGATE_RTSP_PASSWORD=password
    network_mode: host
