services:
  scrypted:
    container_name: scrypted
    image: koush/scrypted
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /home/maccell/scrypted/config:/server/volume
    ports:
      - "11080:11080"
      - "10443:10443"
    privileged: true
    environment:
      - SCRYPTED_WEB_PORT=11080
      - SCRYPTED_SECURE_PORT=10443
