services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.16.3
    privileged: true
    shm_size: "512mb"
    volumes:
      - ./config.yml:/config/config.yml:ro # Tu lógica de conteo aquí
      - ./frigate_db:/db # Base de datos persistente (Usuarios, configuración)
      - /mnt/storage/frigate:/media/frigate # Donde guardas el video en el ProLiant
    network_mode: "host"
